### ISSUE TITLE
Select core vertical sampling scheme

### ISSUE THREAD

**Issue by cgrdn** [ArgoCanada/argo-dm#1]
@blairgreenan @richardsc Could you each take a look at https://github.com/ArgoCanada/argo-dm/blob/main/docs/arvor-parameters.md and provide input on the distribution of vertical samples for the core floats? On our test float we did the following:

- 1 dbar bins from 0 to 250 dbar (250 pts)
- 5 dbar bins from 250 to 500 dbar (50 pts)
- 10 dbar bins below 500 dbar (150 pts)

For a total of 450 points. On plan 3 though, we should have room for about 700 points, so I provided a few options for how we could "spend" those extra data points. Feel free to suggest changes or combinations of different options, just wanted to have a look at some different things we could do. 

Also important: the theoretical max to fill plan 3 is 711 points per profile, so if 700 points feels like flying too close to the sun then we can scale back to 650. I just seemed to be able to pick cleaner depth thresholds with a few more points. 

Finally for reference here is the French ~1000 pt. scheme: 

- 1 dbar bins from 0 to 400 dbar (400 pts)
- 2 dbar bins from 400 to 1400 dbar (500 pts)
- 5 dbar bins below 1400 dbar (120 pts)

**Comment by richardsc** [comment]
Sorry — I missed this. Will try and look ASAP

**Comment by richardsc** [comment]
My preference is for plan B. If 700 is too close, you could cut the 1dbar section back a little, eg to 450 or 475.
